file_format: "1"
id: sboard
name: sboard
type: shield
url: https://github.com/sushanthr/sboard-legacy
requires:
  - pro_micro
features:
  - keys
  - encoder
  - pointer
siblings:
  - sboard_left
  - sboard_right